import { DefaultTheme } from "styled-components";
export const lightTheme: DefaultTheme = {
    bgColor: "#eff3ff",
    textColor: "#1E1E1E",
    btnColor: "#3687FF",
    btnHoverColor: "#3687FF",
    btnTextColor: "#fff",
    accentColor: "#1a5cbd",
    contentColor: "#a9a9a9",
    filedBgColor: "#5573df",
    starBorderColor: "#5573df",
    starFullColor: "#ffc107",
    LikeBtnColor: "#EBB609",
    opacityBgColor: "#a2bee71a",
    boxShadowGrayColor: "#a2bee740",
    boxShadowBlueColor: "#5a9cff66",
    inputBgColor: "#fff",
    circleColor: "#3687FF",
    cardColor: "#fff",
    modeBgColor: "#666666",
    headerBorderColor: "#f0f0f9",
    headerActiveColor: "#fff",
};
export const darkTheme: DefaultTheme = {
    bgColor: "#1E1E1E",
    textColor: "#fff",
    btnColor: "#3687FF",
    btnHoverColor: "#3687FF",
    btnTextColor: "#fff",
    LikeBtnColor: "#EBB609",
    accentColor: "#1a5cbd",
    contentColor: "#f0f0f0",
    filedBgColor: "#5573df",
    starBorderColor: "#5573df",
    starFullColor: "#ffc107",
    opacityBgColor: "#a7b6cc1a",
    boxShadowGrayColor: "#393d4440",
    boxShadowBlueColor: "#5a9cff66",
    inputBgColor: "#4f555f",
    circleColor: "#a7b6cc1a",
    cardColor: "#36363c",
    modeBgColor: "white",
    headerBorderColor: "#737373",
    headerActiveColor: "#666666",
};
