import { DefaultTheme } from "styled-components";
export const lightTheme: DefaultTheme = {
    bgColor: "#eff3ff",
    textColor: "#404040",
    btnColor: "#3687FF",
    btnTextColor: "#fff",
    hoverColor: "#0e3f87",
    accentColor: "#1a5cbd",
    contentColor: "#a9a9a9",
    filedBgColor: "#5573df",
    starBorderColor: "#5573df",
    starFullColor: "#ffc107",
    opacityBgColor: "#a2bee71a",
    boxShadowGrayColor: "#a2bee740",
    boxShadowBlueColor: "#5a9cff66",
    boxShadowHoverColor: "#95a9e070",
    inputBgColor: "#fff",
    circleColor: "#3687FF",
    cardColor: "#fff",
    modeBgColor: "#666666",
    headerBorderColor: "#f0f0f9",
    headerActiveColor: "#fff",
    successColor: "#5573df",
    imgOpacity: 1,
    subTextColor: "#797979",
};
export const darkTheme: DefaultTheme = {
    bgColor: "#1E1E1E",
    textColor: "#fff",
    btnColor: "#3687FF",
    btnTextColor: "#fff",
    hoverColor: "#86b7ff",
    accentColor: "#1a5cbd",
    contentColor: "#f0f0f0",
    filedBgColor: "#5573df",
    starBorderColor: "#5573df",
    starFullColor: "#ffc107",
    opacityBgColor: "#a7b6cc1a",
    boxShadowGrayColor: "#393d4440",
    boxShadowBlueColor: "#5a9cff66",
    boxShadowHoverColor: "#8498d030",
    inputBgColor: "#4f555f",
    circleColor: "#a7b6cc1a",
    cardColor: "#36363c",
    modeBgColor: "white",
    headerBorderColor: "#2e2e2e",
    headerActiveColor: "#222222",
    successColor: "#5573df",
    imgOpacity: 0.8,
    subTextColor: "#bdbdbd",
};
